# config.yaml
# wandb sweep --project esmAAE_llama_all_gene_pareto_sweep_task7 ./config_for_test_model.yaml 
# CUDA_VISIBLE_DEVICES=0 wandb****
## wandb agent huawen-zhong/esmAAE_llama_pareto_sweep_task10/hg64txnk --count 20 # basal
## CUDA_VISIBLE_DEVICES=1 wandb agent huawen-zhong/esmAAE_llama_pareto_sweep_task10/8ls6m4rk --count 20 # generative
program: esmAAE_train_model.py
method: random
name: esmaae_llama_all_gene_with_pareto_sweep_task10_allgo_llama_cluster_sweep
metric:
  goal: minimizes
  name: Target_loss
parameters:
  batch_size: 
    values: [512]
  macrogene_encoder_hidden_size:
    values: [256,512,1024]
  macrogene_decoder_hidden_size:
    values: [256,512,1024]
  latent_size:
    values: [256,512,1024]
  macrogene_encoder_dropout_ratio:
    values: [0.1,0.2,0.3]
  macrogene_decoder_dropout_ratio:
    values: [0.1,0.2,0.3]
  lr_generator:
    min: 0.00001
    max: 0.001
    distribution: log_uniform_values
  lr_encoder:
    min: 0.00001
    max: 0.001
    distribution: log_uniform_values
  lr_discriminator_species:
    min: 0.00001
    max: 0.001
    distribution: log_uniform_values
  lr_discriminator_celltype:
    min: 0.00001
    max: 0.001
    distribution: log_uniform_values
  hidden_size_adversary_species:
    values: [256]
  hidden_size_adversary_celltype:
    values: [256]
  train_epochs:
    values: [500]
  grad_normalized_type:
    values: ['l2','loss+']
  num_llama_macrogene:
    values: [100,500,1000,1500]
command:
  - python
  - ${program}
  - "--h5ad_files"
  - '../data/task10_fish.h5ad' 
  - '../data/task10_fly.h5ad' 
  - "--species_labels"
  - 'fish'
  - 'fly' 
  - "--celltype_labels" 
  - 'cell_lineage' 
  - 'cell_lineage' 
  - "--output_path"
  - './models/task10_sweep'
  - "--gene_esm_embedding_path"
  - '../gene_embeddings/task10_fish_v11.gene_symbol_to_embedding_ESM1b.pt'
  - '../gene_embeddings/task10_fly.gene_symbol_to_embedding_ESM1b.pt'
  - "--gene_llama_embedding_path"
  - '../gene_go_term/only_BP_embedding/task10_fish_llama2-7B_gene_embeddings.pt'
  - '../gene_go_term/only_BP_embedding/task10_fly_llama2-7B_gene_embeddings.pt'
  - "--num_esm_macrogene"
  - 2000
  - "--highly_variable_genes"
  - 8000
  - "--evaluate_emb"
  - 'True'


#  wandb agent huawen-zhong/esmAAE_llama_all_gene_pareto_sweep_task3/q9kwjmff --count 20
# CUDA_VISIBLE_DEVICES=1 wandb agent huawen-zhong/esmAAE_llama_all_gene_pareto_sweep_task7/4js4mbey  --count 20
